### ISSUE TITLE
Implementation 

### ISSUE THREAD

**Issue by edegraaff** [adrianrudnik/fritzbox-cloudflare-dyndns#15]
Hi, 
I have a FritzBox and i need to give up my static ip nr, i have my own DNS at a hosting provider, is it possible by using your code on a pi to update the dns with new dynamic ipnrs? 

regards
Eelco

**Comment by cromefire** [comment]
It only works for Cloudflare DNS and I currently have no plan to extend that as that is what I use and it's free (just get a Cloudflare account, set the DNS servers Cloudflare gives you at your hosting provider and then you can use this).

**Comment by edegraaff** [comment]
Clear thanks, cloudflare would work for me
