### ISSUE TITLE
Possible Issue with TR64?

### ISSUE THREAD

**Issue by vr6syncro** [adrianrudnik/fritzbox-cloudflare-dyndns#22]
Is there a change within the Fritzbox TR64?

This Script stopped working for me.

I get the 404 Error Message from the Fritzbox but the log say: 

```

time="2023-11-20T14:52:08Z" level=warning msg="Failed to poll WAN IPv4 from router" error="Post \"http://192.168.99.1:49000/igdupnp/control/WANIPConn1\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"

```

**Comment by cromefire** [comment]
Sure it can reach the FritzBox? That isn't a 404, but a connection timeout. Can you try with curl or so?

**Comment by vr6syncro** [comment]
mh you are right, my bad id did only check it with my pc not my server. pc can reach but server not... they are on the same network and the server only cant reach the fritzbox... strange but not related to this script.

Thanks for the reply

**Comment by cromefire** [comment]
No problem
