### ISSUE TITLE
Failed to poll WAN IPv4 from router error (connect: connection refused)

### ISSUE THREAD

**Issue by totti4ever** [adrianrudnik/fritzbox-cloudflare-dyndns#25]
Hey guys, my service stopped in the last days producing this error message:
cloudflare-dns-update    | 2024/07/26 20:21:13 WARN Failed to poll WAN IPv4 from router error="Post \"http://fritz.box:49000/igdupnp/control/WANIPConn1\": dial tcp 192.168.178.1:49000: connect: connection refused"

If I try to open the main fritzbox page from the server or from within the docker container (i.e. Login), I get a 404 error message. If I try the very same command from my Laptop, everything works.

I'm pretty sure that I had some similar issue a couple of years ago, when the fritzbox blocked my servers IP address. I just can't find anything on that and especially not how to unblock it.

Any ideas, thanks a lot!

P.S.: Restarted the container and the box, no change

**Comment by cromefire** [comment]
The is a block list in
Internet > Filter > Listen > IP-Sperrlisten
Maybe that's the issue. I've never seen this issue before so I can't help much beyond that.
![Screenshot_20240726-224606.png](https://github.com/user-attachments/assets/82c1893c-4c1b-48bb-afb7-a40dfe3d9010)

**Comment by cromefire** [comment]
Closing this as this seems more on a configuration / network issue that I can't help with much more. It's not locked so anyone can still comment, but I want the issues to be nice and tidy.
