### ISSUE TITLE
Invalid server bind does not cause application to exit

### ISSUE THREAD

**Issue by britter** [adrianrudnik/fritzbox-cloudflare-dyndns#26]
I miss-configured the value for `DYNDNS_SERVER_BIND` with `8080` instead of `:8080`. However when I started fritzbox-cloudflare-dyndns the application kept running instead of exiting with a non-zero exit code. I think that is because binding to the port happens inside of a go routine and that swallows the error state instead of returning it to the top level [here](https://github.com/cromefire/fritzbox-cloudflare-dyndns/blob/main/main.go#L155-L158).

Also in the same area of the code, the error log for the http server is configured to with info log level. Is that deliberate ([here](https://github.com/cromefire/fritzbox-cloudflare-dyndns/blob/main/main.go#L150))?

**Comment by cromefire** [comment]
> I think that is because binding to the port happens inside of a go routine and that swallows the error state instead of returning it to the top level [here](https://github.com/cromefire/fritzbox-cloudflare-dyndns/blob/main/main.go#L155-L158).

Might well be... Sadly I think that's beyond my skills in go, so if you want to propose a fix, be my guest.

> Also in the same area of the code, the error log for the http server is configured to with info log level. Is that deliberate ([here](https://github.com/cromefire/fritzbox-cloudflare-dyndns/blob/main/main.go#L150))?

I'd think probably not? But I didn't write this code I only maintain it to the best of my abilities, so I'd say that should probably be on an error or at least warning level.

**Comment by britter** [comment]
Hey @cromefire, thank for responding. I'd love to help, but it's also the first Go code base I'm dealing with. I'll have a look, but I'm not too confident I can pull this off.

**Comment by adrianrudnik** [comment]
Hi there, simplest way would be to introduce a context, i'll look into a simple fix.
