### ISSUE TITLE
Cloudflare proxy status

### ISSUE THREAD

**Issue by Ozafy** [adrianrudnik/fritzbox-cloudflare-dyndns#3]
When the service updates the cloudflare dns record it resets the proxy status to false even when it was set to true manually before the update.

It would be great if it keeps the existing value or if it was a configurable setting.

**Comment by adrianrudnik** [comment]
Thanks for the report, working on a simple workaround for it. Escalated it also to https://github.com/cloudflare/cloudflare-go/issues/563

**Comment by adrianrudnik** [comment]
Fixed in docker tags `latest` and `1.1.1`.
