### ISSUE TITLE
Feature request: Read secrets from files

### ISSUE THREAD

**Issue by britter** [adrianrudnik/fritzbox-cloudflare-dyndns#30]
I'm deploying this service on [NixOS](https://nixos.org) as a systemd unit and I manage secrets using [sops](https://github.com/getsops/sops). A common practice in this space is for applications to read the location of a file containing a secret from the system environment, instead of reading the secret itself from the environment.

For this reason I'd like to be able to configure `DYNDNS_SERVER_PASSWORD_FILE` environment variable that contains the path to a file with the password. The application should inspect this variable in case `DYNDNS_SERVER_PASSWORD` is not set and try to read the password from the file specified that way. Same for `CLOUDFLARE_API_TOKEN`: The application should try to read the token from a file specified via `CLOUDFLARE_API_TOKEN_FILE` in case `CLOUDFLARE_API_TOKEN` is not set.

**Comment by britter** [comment]
If this is something the maintainers would be willing to include, I'd like to give implementing this a try.

**Comment by cromefire** [comment]
Would be good for Docker as well as then you can use Docker & Kubernetes secrets.

**Comment by britter** [comment]
Okay, I'll look into it!

**Comment by adrianrudnik** [comment]
Just to chime in: It adds additional security risks of secrets being included in system backups and alike (like actual .env files instead of native environmental variables). Docker already comes with `docker secret` and the respective [secret managment](https://docs.docker.com/compose/how-tos/use-secrets/).

Could this be something a simple `$(cat whatever)` could do beforehand?

**Comment by cromefire** [comment]
> Docker already comes with docker secret and the respective secret managment.

Which requires you to read the secret from a file (Kubernetes as well), which is exactly why more and more apps support reading secrets from files. In the end it's just an option as well, so you don't need to do it this way.

A big issue with environment variables in docker though is that they are just floating around in the container metadata, making it easy to accidentally leak somewhere.

**Comment by britter** [comment]
I'm working on adding it [here](https://github.com/britter/fritzbox-cloudflare-dyndns/commit/486ae93a2afa637799e0c43d732a162a502a2fac). Just need to test this before creating the PR.
