### ISSUE TITLE
Add support for ARM-architecture

### ISSUE THREAD

**Issue by AlexKnowsIt** [adrianrudnik/fritzbox-cloudflare-dyndns#5]
Hi,
when I try to run the docker container I get an `standard_init_linux.go:219: exec user process caused: exec format error`. I used it one time with the environment variables for polling and one time for pushing but I get immediately this error.

**Comment by AlexKnowsIt** [comment]
I think I found out the problem already, I tried to run it on a Pi and it seems arm isn't supported am I right?

**Comment by adrianrudnik** [comment]
It's an ARM machine or? It's not working with the docker image, but it should work as a compiled version.

Try to clone the repository and change the line 13 in the Dockerfile to something like

```
&& GOOS=linux GOARCH=arm GOARM=5  go build -mod=vendor -o server
```

and do the parts mentioned in https://github.com/adrianrudnik/fritzbox-cloudflare-dyndns#docker-build

Might try to offer arm build myself, just not today. It should possible to compile for ARM though.

**Comment by AlexKnowsIt** [comment]
Thanks, I will try that out! A docker image for arm would be quite nice in general I think. Would be a perfect combination to run it with home assistant and let it update the IP-Adress from the always on device :)

**Comment by AlexKnowsIt** [comment]
I changed the title because the issue isn't a real issue its more an idea for enhancement. I have it running now on a different machine so I will probably not have time to build a ARM-docker image by myself. Would still be happy to see it especially because this app is so lightweight it could also be run on a Pi zero.

**Comment by cromefire** [comment]
The new container is a multi-platform image: https://github.com/cromefire/fritzbox-cloudflare-dyndns/pkgs/container/fritzbox-cloudflare-dyndns

It doesn't have a versioned tag yet, but I'll probably do one today.
