### ISSUE TITLE
Support retry

### ISSUE THREAD

**Issue by cromefire** [adrianrudnik/fritzbox-cloudflare-dyndns#6]
I recently had the problem that when restarting the FritzBox after the new IP was discovered, the API call still failed because the internet still wasn't online. Some retry might be good here or maybe some improvement in the polling / saving the last set IP.

**Comment by adrianrudnik** [comment]
Cool, will try to look at it later and merge it if it works on my end. I'm fine with manual testing right now, it's a basic project and mocking two external services (esp. SOAP) and all their scenarios is just not in my time budget right now.

**Comment by cromefire** [comment]
Yeah but I couldn't figure out a manual test case either (short of restarting my Fritzbox and even that doesn't ensure the error occurs), some blocking or routing table stuff might to it but I'm currently not into that enough
