### ISSUE TITLE
Disable strategy

### ISSUE THREAD

**Issue by danielbeicht** [adrianrudnik/fritzbox-cloudflare-dyndns#8]
Is it possible to disable e.g. the polling strategy if I only want to use the pushing strategy?

**Comment by adrianrudnik** [comment]
Sure, just do not specify FRITZBOX_ENDPOINT_URL, you should see a message on the log that indicates that polling was disabled due to this missing env.

**Comment by danielbeicht** [comment]
When I don't specify the FRITZBOX_ENDPOINT_URL it's throwing an error:
![image](https://user-images.githubusercontent.com/15012334/115161983-03458a80-a0a1-11eb-835b-31d5784c8100.png)

When I uncomment the FRITZBOX-lines, the container is working and I can use the pushing strategy (however, polling strategy running too which I want to disable).

**Comment by DHeinrichs** [comment]
@danielbeicht I found an ugly but working quick fix: Just add an empty environment var like 
```yml
environment:
      - FRITZBOX_ENDPOINT_URL=
      - other stuff
```

**Comment by cromefire** [comment]
Improved the documentation on that to say that you need to explicitly set `FRITZBOX_ENDPOINT_URL` to an empty string for the docker image.
